# Gradle Properties for Lyhty
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.java.home=/opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home
android.useAndroidX=true
android.nonFinalResIds=true
kotlin.code.style=official
org.gradle.experimental.privacysandbox.sdk.plugin.enable=false
